import type { Schema } from '@/lib/types';

/**
 * Generate Markdown documentation for a schema.
 */
export function generateSchemaDoc(schema: Schema): string {
  const lines: string[] = [];

  lines.push(`# ${schema.name}`);
  lines.push('');
  lines.push(`> Generated by DBMate on ${new Date().toISOString().split('T')[0]}`);
  lines.push(`> Dialect: ${schema.dialect}`);
  lines.push(`> Tables: ${schema.tables.length}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // Table of contents
  lines.push('## Table of Contents');
  lines.push('');
  for (const table of schema.tables) {
    lines.push(`- [${table.name}](#${table.name.toLowerCase().replace(/_/g, '-')})`);
  }
  lines.push('');
  lines.push('---');
  lines.push('');

  // Table details
  for (const table of schema.tables) {
    lines.push(`## ${table.name}`);
    lines.push('');
    if (table.comment) {
      lines.push(`> ${table.comment}`);
      lines.push('');
    }

    // Columns
    lines.push('### Columns');
    lines.push('');
    lines.push('| Column | Type | Nullable | PK | Default | Comment |');
    lines.push('|--------|------|----------|-----|---------|---------|');
    for (const col of table.columns) {
      const pk = col.primaryKey ? 'Yes' : '';
      const nullable = col.nullable ? 'Yes' : 'No';
      const def = col.defaultValue ?? '';
      const comment = col.comment ?? '';
      lines.push(`| ${col.name} | ${col.type} | ${nullable} | ${pk} | ${def} | ${comment} |`);
    }
    lines.push('');

    // Indexes
    if (table.indexes.length > 0) {
      lines.push('### Indexes');
      lines.push('');
      lines.push('| Name | Columns | Unique |');
      lines.push('|------|---------|--------|');
      for (const idx of table.indexes) {
        lines.push(`| ${idx.name} | ${idx.columns.join(', ')} | ${idx.unique ? 'Yes' : 'No'} |`);
      }
      lines.push('');
    }

    // Foreign Keys
    if (table.foreignKeys.length > 0) {
      lines.push('### Foreign Keys');
      lines.push('');
      lines.push('| Columns | References | On Delete | On Update |');
      lines.push('|---------|-----------|-----------|-----------|');
      for (const fk of table.foreignKeys) {
        const onDel = fk.onDelete ?? '-';
        const onUpd = fk.onUpdate ?? '-';
        lines.push(
          `| ${fk.columns.join(', ')} | ${fk.referencedTable}(${fk.referencedColumns.join(', ')}) | ${onDel} | ${onUpd} |`
        );
      }
      lines.push('');
    }

    lines.push('---');
    lines.push('');
  }

  return lines.join('\n');
}
