'use client';

import { useCallback, useState } from 'react';
import { useRouter } from 'next/navigation';
import {
  ArrowLeft,
  Check,
  Copy,
  Database,
  Download,
  FileCode,
  FileText,
  GitBranch,
  Image,
  Loader2,
  Package,
  Sprout,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { ScrollArea } from '@/components/ui/scroll-area';
import { useSchemaStore } from '@/stores/schema-store';
import { generateSchemaDoc } from '@/lib/doc-generator';
import { formatMigration } from '@/lib/migration-formatter';
import { toast } from 'sonner';
import type { Migration, MigrationFormat } from '@/lib/types';
import { PageTransition, StaggerContainer, StaggerItem } from '@/components/shared/motion';

function downloadFile(content: string, filename: string, mime = 'text/plain') {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

async function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export default function ExportPage() {
  const router = useRouter();
  const { currentSchema, healthReport, migrations } = useSchemaStore();
  const [preview, setPreview] = useState<string>('');
  const [previewTitle, setPreviewTitle] = useState('');
  const [copied, setCopied] = useState(false);
  const [isExporting, setIsExporting] = useState(false);

  // Schema SQL export
  const handleExportSQL = useCallback(() => {
    if (!currentSchema) return;
    const header = `-- Generated by DBMate\n-- Schema: ${currentSchema.name}\n-- Date: ${new Date().toISOString().split('T')[0]}\n-- Dialect: ${currentSchema.dialect}\n\n`;
    const content = header + currentSchema.rawSQL;
    setPreview(content);
    setPreviewTitle('Schema SQL');
    downloadFile(content, `${currentSchema.name}.sql`, 'text/sql');
    toast.success('Schema SQL downloaded');
  }, [currentSchema]);

  // Migrations export
  const handleExportMigrations = useCallback(async () => {
    if (!currentSchema || migrations.length === 0) {
      toast.error('No migrations to export');
      return;
    }
    setIsExporting(true);
    try {
      // Load migrations
      const res = await fetch(
        `/api/migrate?schemaId=${encodeURIComponent(currentSchema.id)}`
      );
      const data = await res.json();
      const migs: Migration[] = data.migrations ?? migrations;

      if (migs.length === 0) {
        toast.error('No migrations found');
        return;
      }

      const { default: JSZip } = await import('jszip');
      const zip = new JSZip();
      const folder = zip.folder('migrations')!;

      for (const m of migs) {
        const formatted = formatMigration(m, m.format as MigrationFormat);
        folder.file(`${m.version}__${m.name}.sql`, formatted);
      }

      const blob = await zip.generateAsync({ type: 'blob' });
      await downloadBlob(blob, `${currentSchema.name}_migrations.zip`);

      setPreview(migs.map((m) => `-- ${m.version}: ${m.name}\n${m.upSQL}`).join('\n\n'));
      setPreviewTitle('Migrations');
      toast.success(`${migs.length} migrations exported`);
    } catch {
      toast.error('Failed to export migrations');
    } finally {
      setIsExporting(false);
    }
  }, [currentSchema, migrations]);

  // Seed data export (redirect to seed page)
  const handleExportSeed = useCallback(() => {
    router.push('/seed');
  }, [router]);

  // ER Diagram export
  const handleExportERDiagram = useCallback(async () => {
    setIsExporting(true);
    try {
      const { toPng } = await import('html-to-image');
      const el = document.querySelector('.react-flow') as HTMLElement;
      if (!el) {
        toast.error('ER Diagram not rendered. Visit Dashboard first.');
        return;
      }
      const dataUrl = await toPng(el, { quality: 1, pixelRatio: 2 });
      const link = document.createElement('a');
      link.href = dataUrl;
      link.download = `${currentSchema?.name ?? 'schema'}_er_diagram.png`;
      link.click();
      toast.success('ER Diagram exported as PNG');
    } catch {
      toast.error('Failed to export ER Diagram. Visit Dashboard first to render it.');
    } finally {
      setIsExporting(false);
    }
  }, [currentSchema]);

  // Documentation export
  const handleExportDocs = useCallback(() => {
    if (!currentSchema) return;
    const doc = generateSchemaDoc(currentSchema);
    setPreview(doc);
    setPreviewTitle('Documentation');
    downloadFile(doc, `${currentSchema.name}_docs.md`, 'text/markdown');
    toast.success('Documentation downloaded');
  }, [currentSchema]);

  // Full bundle export
  const handleExportBundle = useCallback(async () => {
    if (!currentSchema) return;
    setIsExporting(true);
    try {
      const { default: JSZip } = await import('jszip');
      const zip = new JSZip();

      // Schema SQL
      const header = `-- Generated by DBMate\n-- Schema: ${currentSchema.name}\n-- Date: ${new Date().toISOString().split('T')[0]}\n-- Dialect: ${currentSchema.dialect}\n\n`;
      zip.file('schema.sql', header + currentSchema.rawSQL);

      // Schema JSON
      zip.file('schema.json', JSON.stringify(currentSchema, null, 2));

      // Documentation
      const doc = generateSchemaDoc(currentSchema);
      zip.file('docs.md', doc);

      // Health report
      if (healthReport) {
        zip.file('health_report.json', JSON.stringify(healthReport, null, 2));
      }

      // Migrations
      let migs: Migration[] = [];
      try {
        const res = await fetch(
          `/api/migrate?schemaId=${encodeURIComponent(currentSchema.id)}`
        );
        const data = await res.json();
        migs = data.migrations ?? [];
      } catch {
        // non-critical
      }

      if (migs.length > 0) {
        const folder = zip.folder('migrations')!;
        for (const m of migs) {
          const formatted = formatMigration(m, m.format as MigrationFormat);
          folder.file(`${m.version}__${m.name}.sql`, formatted);
        }
      }

      const blob = await zip.generateAsync({ type: 'blob' });
      await downloadBlob(blob, `${currentSchema.name}_bundle.zip`);
      toast.success('Full bundle exported');
    } catch {
      toast.error('Failed to export bundle');
    } finally {
      setIsExporting(false);
    }
  }, [currentSchema, healthReport]);

  // Copy preview
  const handleCopyPreview = useCallback(async () => {
    if (!preview) return;
    await navigator.clipboard.writeText(preview);
    setCopied(true);
    toast.success('Copied');
    setTimeout(() => setCopied(false), 2000);
  }, [preview]);

  // No schema loaded
  if (!currentSchema) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh] gap-4 text-center">
        <Download className="h-12 w-12 text-muted-foreground" />
        <h2 className="text-2xl font-semibold">Export</h2>
        <p className="text-muted-foreground max-w-md">
          Import a schema first to export data.
        </p>
        <Button variant="outline" onClick={() => router.push('/')}>
          <ArrowLeft className="h-4 w-4 mr-2" />
          Go to Import
        </Button>
      </div>
    );
  }

  const exportCards = [
    {
      icon: Database,
      title: 'Schema SQL',
      desc: 'Complete schema as CREATE TABLE statements',
      action: handleExportSQL,
    },
    {
      icon: GitBranch,
      title: 'Migrations',
      desc: 'All migration files bundled as ZIP',
      action: handleExportMigrations,
    },
    {
      icon: Sprout,
      title: 'Seed Data',
      desc: 'Generate and download test data',
      action: handleExportSeed,
    },
    {
      icon: Image,
      title: 'ER Diagram',
      desc: 'Visual diagram export as PNG',
      action: handleExportERDiagram,
    },
    {
      icon: FileText,
      title: 'Documentation',
      desc: 'Auto-generated Markdown docs',
      action: handleExportDocs,
    },
    {
      icon: Package,
      title: 'Full Bundle',
      desc: 'Everything in a ZIP file',
      action: handleExportBundle,
    },
  ];

  return (
    <PageTransition>
    <div className="max-w-4xl mx-auto space-y-6 p-4">
      {/* Header */}
      <div className="flex items-center gap-3">
        <Download className="h-5 w-5 text-primary" />
        <h2 className="text-xl font-semibold">Export</h2>
        <span className="text-sm text-muted-foreground">
          {currentSchema.name}
        </span>
      </div>

      {/* Export cards grid */}
      <StaggerContainer className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
        {exportCards.map(({ icon: Icon, title, desc, action }) => (
          <StaggerItem key={title}>
          <Card
            className="cursor-pointer hover:border-primary/40 transition-colors h-full"
            onClick={action}
          >
            <CardHeader className="pb-2">
              <div className="flex items-center gap-2">
                <Icon className="h-4 w-4 text-primary" />
                <CardTitle className="text-sm">{title}</CardTitle>
              </div>
            </CardHeader>
            <CardContent>
              <p className="text-xs text-muted-foreground">{desc}</p>
              <Button
                variant="outline"
                size="sm"
                className="mt-3 w-full h-7 text-xs"
                disabled={isExporting}
              >
                {isExporting ? (
                  <Loader2 className="h-3 w-3 mr-1 animate-spin" />
                ) : (
                  <Download className="h-3 w-3 mr-1" />
                )}
                Download
              </Button>
            </CardContent>
          </Card>
          </StaggerItem>
        ))}
      </StaggerContainer>

      {/* Preview */}
      {preview && (
        <Card>
          <CardHeader className="pb-2">
            <div className="flex items-center justify-between">
              <CardTitle className="text-sm flex items-center gap-2">
                <FileCode className="h-4 w-4" />
                Preview: {previewTitle}
              </CardTitle>
              <Button
                variant="ghost"
                size="sm"
                onClick={handleCopyPreview}
                className="h-7 text-xs"
              >
                {copied ? (
                  <Check className="h-3 w-3 mr-1 text-green-500" />
                ) : (
                  <Copy className="h-3 w-3 mr-1" />
                )}
                Copy
              </Button>
            </div>
          </CardHeader>
          <CardContent>
            <ScrollArea className="h-64">
              <pre className="text-xs font-mono bg-muted/50 p-3 rounded border whitespace-pre-wrap">
                {preview}
              </pre>
            </ScrollArea>
          </CardContent>
        </Card>
      )}
    </div>
    </PageTransition>
  );
}
